"use client";

import { useEffect, useRef, useState } from "react";

const ADSTERRA_SRC =
  "https://pl31209749.profitableratecpmnetwork.com/839a36ce65a197c2f9ac39c8e70ca81e/invoke.js";
const CONTAINER_ID = "container-839a36ce65a197c2f9ac39c8e70ca81e";

/**
 * NativeAd — Phase 2 polished sponsored shell around the proven /ad-test implementation.
 * Preserves exact Adsterra script + container id. Script injected once (StrictMode safe).
 * Outer Nexuss-native shell is UI-only; inner creative is untouched Adsterra HTML.
 * Empty inventory collapses shell to avoid blank space (Chromium).
 */
export default function NativeAd() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [hasContent, setHasContent] = useState(false);

  useEffect(() => {
    if (document.querySelector(`script[src="${ADSTERRA_SRC}"]`)) {
      // script already present — still need observers for existing container
    } else {
      const s = document.createElement("script");
      s.async = true;
      s.setAttribute("data-cfasync", "false");
      s.src = ADSTERRA_SRC;
      document.body.appendChild(s);
    }
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const check = () => {
      const childCount = el.children.length;
      const rectH = el.getBoundingClientRect().height;
      const htmlLen = el.innerHTML.trim().length;
      // Adsterra injects ~6k HTML and 2 children with ~250px height when filled
      if (childCount > 0 && (rectH > 20 || htmlLen > 300)) {
        setHasContent(true);
      }
    };

    check();

    const mo = new MutationObserver(check);
    mo.observe(el, { childList: true, subtree: true });

    const ro = new ResizeObserver(check);
    ro.observe(el);

    const interval = setInterval(check, 600);
    const timeout = setTimeout(() => clearInterval(interval), 15000);

    return () => {
      mo.disconnect();
      ro.disconnect();
      clearInterval(interval);
      clearTimeout(timeout);
    };
  }, []);

  return (
    <div
      className={`w-full max-w-full overflow-hidden transition-all duration-300 ${
        hasContent
          ? "mt-3 opacity-100"
          : "pointer-events-none max-h-0 opacity-0 m-0 overflow-hidden border-0 p-0"
      }`}
      aria-label="Sponsored advertisement"
      data-has-content={hasContent ? "true" : "false"}
    >
      <div
        className={`rounded-2xl border bg-zinc-900/50 backdrop-blur-sm ${
          hasContent ? "border-zinc-800 p-3 sm:p-3.5" : "border-transparent p-0"
        }`}
      >
        {/* Subtle Nexuss-native header — outside Adsterra creative */}
        <div className="flex items-center gap-2 px-1 pb-2.5">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-zinc-700/60 bg-zinc-800/80 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-widest text-zinc-400">
            <span className="h-1.5 w-1.5 rounded-full bg-amber-400/80" aria-hidden />
            Sponsored
          </span>
          <span className="h-px flex-1 bg-gradient-to-r from-zinc-800 to-transparent" aria-hidden />
          <span className="text-[10px] tracking-wide text-zinc-600">Advertisement</span>
        </div>

        {/* Real Adsterra content — untouched */}
        <div className="rounded-xl border border-zinc-800 bg-zinc-950 overflow-hidden">
          <div
            ref={containerRef}
            id={CONTAINER_ID}
            className="w-full max-w-full [&_img]:max-w-full [&_img]:h-auto"
          />
        </div>

        <p className="mt-2 px-1 text-[10px] leading-none text-zinc-600">
          Sponsored content • Not generated by AI
        </p>
      </div>
    </div>
  );
}
